# Problema do Négocio

A empresa está com dificuldades na área de revenda dos automóveis usados em seu catálogo.

Para resolver esse problema, a empresa comprou uma base de dados de um marketplace de compra e venda para entender melhor o mercado nacional, de forma a conseguir precificar o seu catálogo de forma mais competitiva e assim recuperar o mau desempenho neste setor.

Seu objetivo é analisar os dados para responder às perguntas de negócios feitas pelo cliente e criar um modelo preditivo que precifique os carros do cliente de forma que eles fiquem o mais próximos dos valores de mercado.

# Analise Exploratoria dos Dados

### Pacotes Usados

In [4]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#### Carregamento
Para carregar os dados foi verificado que ele tinha a separação pelo caracter tab, usando a codificação UTF-16 LE, para analise de dados foi optado realizar um merge entre as bases

In [3]:
cars_test:pd.DataFrame = pd.read_csv('/home/raullima/Documentos/Desafio Cientista de Dados 2023 9/data/cars_test.csv',encoding='UTF-16LE', sep='\t')
cars_train:pd.DataFrame = pd.read_csv('/home/raullima/Documentos/Desafio Cientista de Dados 2023 9/data/cars_train.csv',encoding='UTF-16LE', sep='\t')

In [4]:
cars_train.head()

id  num_fotos       marca   modelo  \
0  300716223898539419613863097469899222392        8.0      NISSAN    KICKS   
1  279639842134129588306469566150288644214        8.0        JEEP  COMPASS   
2   56414460810621048900295678236538171981       16.0         KIA  SORENTO   
3   56862509826849933428086372390159405545       14.0  VOLKSWAGEN   AMAROK   
4  338980975753200343894519909855598027197        8.0   SSANGYONG  KORANDO   

                                              versao  ano_de_fabricacao  \
0                    1.6 16V FLEXSTART SL 4P XTRONIC               2017   
1                    2.0 16V FLEX LIMITED AUTOMÁTICO               2017   
2              2.4 16V GASOLINA EX 7L AWD AUTOMÁTICO               2018   
3  2.0 HIGHLINE 4X4 CD 16V TURBO INTERCOOLER DIES...               2013   
4         2.0 GLS 4X4 16V TURBO DIESEL 4P AUTOMÁTICO               2013   

   ano_modelo  hodometro      cambio  num_portas                  tipo  \
0      2017.0    67772.0         CVT           4                  Sedã   
1      2017.0    62979.0  Automática           4                  Sedã   
2      2019.0    44070.0  Automática           4                  Sedã   
3      2015.0    85357.0  Automática           4                Picape   
4      2015.0    71491.0  Automática           4  Utilitário esportivo   

  blindado     cor tipo_vendedor cidade_vendedor      estado_vendedor  \
0        N  Branco            PF  Rio de Janeiro       São Paulo (SP)   
1        N  Branco            PF  Belo Horizonte    Minas Gerais (MG)   
2        N   Preto            PJ          Santos       São Paulo (SP)   
3        N  Branco            PJ        Sorocaba       São Paulo (SP)   
4        N   Preto            PF  Rio de Janeiro  Rio de Janeiro (RJ)   

      anunciante  entrega_delivery  troca  elegivel_revisao dono_aceita_troca  \
0  Pessoa Física             False  False             False               NaN   
1  Pessoa Física             False  False             False      Aceita troca   
2           Loja              True  False             False      Aceita troca   
3           Loja              True   True             False      Aceita troca   
4  Pessoa Física             False  False             False               NaN   

  veiculo_único_dono                       revisoes_concessionaria  ipva_pago  \
0                NaN  Todas as revisões feitas pela concessionária  IPVA pago   
1                NaN                                           NaN  IPVA pago   
2                NaN                                           NaN        NaN   
3                NaN                                           NaN  IPVA pago   
4                NaN  Todas as revisões feitas pela concessionária        NaN   

  veiculo_licenciado  garantia_de_fábrica  \
0         Licenciado                  NaN   
1                NaN                  NaN   
2                NaN                  NaN   
3         Licenciado                  NaN   
4                NaN  Garantia de fábrica   

                          revisoes_dentro_agenda  veiculo_alienado  \
0                                            NaN               NaN   
1                                            NaN               NaN   
2                                            NaN               NaN   
3                                            NaN               NaN   
4  Todas as revisões feitas pela agenda do carro               NaN   

           preco  
0   74732.590084  
1   81965.332634  
2  162824.814472  
3  123681.358857  
4   82419.763891

- Foi analisado que alguns dados estavam com valores categorios e numéricos
sua conversão para valores numéricos, para realizar o treinamento do modelo e EDA.
- Existe também alguams possiveis features que não servem para nenhuma análise ou aplicação sendo elas: id, num_fotos.
- Q1: Com base neste dataset queremos identificar quais são os fatores que mais influenciam no preço de um carro.
- Q2: Quais são os carros mais caros e mais baratos?
- Q3: Quais são os carros mais vendidos?

### EDA

In [7]:
cars_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29584 entries, 0 to 29583
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       29584 non-null  object 
 1   num_fotos                29407 non-null  float64
 2   marca                    29584 non-null  object 
 3   modelo                   29584 non-null  object 
 4   versao                   29584 non-null  object 
 5   ano_de_fabricacao        29584 non-null  int64  
 6   ano_modelo               29584 non-null  float64
 7   hodometro                29584 non-null  float64
 8   cambio                   29584 non-null  object 
 9   num_portas               29584 non-null  int64  
 10  tipo                     29584 non-null  object 
 11  blindado                 29584 non-null  object 
 12  cor                      29584 non-null  object 
 13  tipo_vendedor            29584 non-null  object 
 14  cidade_vendedor       

- No dataframe de Treinamento temos 1.9 de Mega Bytes de dados, sendo eles do tipo objeto, inteiro, float e boleano

In [8]:
cars_train.describe()

num_fotos  ano_de_fabricacao    ano_modelo      hodometro  \
count  29407.000000       29584.000000  29584.000000   29584.000000   
mean      10.323834        2016.758552   2017.808985   58430.592077   
std        3.487334           4.062422      2.673930   32561.769309   
min        8.000000        1985.000000   1997.000000     100.000000   
25%        8.000000        2015.000000   2016.000000   31214.000000   
50%        8.000000        2018.000000   2018.000000   57434.000000   
75%       14.000000        2019.000000   2020.000000   81953.500000   
max       21.000000        2022.000000   2023.000000  390065.000000   

         num_portas  veiculo_alienado         preco  
count  29584.000000               0.0  2.958400e+04  
mean       3.940677               NaN  1.330239e+05  
std        0.338360               NaN  8.166287e+04  
min        2.000000               NaN  9.869951e+03  
25%        4.000000               NaN  7.657177e+04  
50%        4.000000               NaN  1.143558e+05  
75%        4.000000               NaN  1.636796e+05  
max        4.000000               NaN  1.359813e+06

- Neste dataset existe 29407 numero de fotos, 0 veiculo alienado ou seja contêm variavel nula ou está vazio, 29584 anos de fabricação, ano de modelo e hodometro
- O valor maximo de ano de fabricação é de 2022 e de modelo é 2023, numero de portas é de 4, com preço 1.359813e+06.
- O valor minimo de fabricação é de 1985, modelo é 1997, numero de portas 2, com preço de
- 25% dos carros têm 8 fotos, têm o ano de modelo de 2015 e fabrica de 2016, com 31235 de km rodados, com 4 portas no preço de 9.869951e+03.
- 50% dos carros têm em torno de 8 fotos também, o ano de fabricão é 2018, ano de modelo 2018, com 57244 de kilometros rodados, com 4 portas
- 75% dos carros têm em torno de 8 fotos também, o ano de fabricão é 2018, ano de modelo 2018, com 57244 de kilometros rodados, com 4 portas
- A Media dos dados são de  10 numero de fotos, 2016 e 2017 é o ano de fabricação e de modelo médio da maioria dos carros
- O Desvio padão dos dados, no ano de modelo é 4 anos e de fabricaçaõ 2 anos e com preço 8.166287e+04, logo temos uma grande variação de preço, ano de modelo, fabricação de km rodados.

* Q1: nos informa que 25% dos carros têm 8 fotos, têm o ano de modelo de 2015 e fabrica de 2016, com 31235 de km rodados, com 4 portas no preço de 9.869951e+03 e 75% dos carros têm o ano de fabricão, ano de modelo, kilometros rodados e portas maiores que 25% dos carros.

* Q2: nos informa que 50% dos carros têm em torno de 8 fotos também, o ano de fabricão é 2018, ano de modelo 2018, com 57244 de kilometros rodados, com 4 portas, e que 50% dos carros têm o ano de fabricão, ano de modelo, kilometros rodados e portas maiores que 50% dos carros.

* Q3: nos informa que 75% dos carros têm em torno de 8 fotos também, o ano de fabricão é 2018, ano de modelo 2018, com 57244 de kilometros rodados, com 4 portas, e que 75% dos carros têm o ano de fabricão, ano de modelo, kilometros rodados e portas maiores que 75% dos carros.


In [9]:
cars_train.groupby(["tipo","estado_vendedor","cambio"]).agg({"preco":"min"}).sort_values("preco")

preco
tipo                 estado_vendedor          cambio                              
Sedã                 Santa Catarina (SC)      Manual                   9869.950645
                     São Paulo (SP)           Manual                  11606.398045
Hatchback            São Paulo (SP)           Manual                  13576.401422
Picape               São Paulo (SP)           Manual                  13642.891063
Hatchback            Rio de Janeiro (RJ)      Manual                  14302.713470
                     Minas Gerais (MG)        Manual                  14464.694571
Sedã                 Minas Gerais (MG)        Manual                  15420.373080
Picape               São Paulo (SP)           Automática              15953.204811
                     Rio de Janeiro (RJ)      Manual                  16264.967340
                     Minas Gerais (MG)        Manual                  17720.564700
Hatchback            São Paulo (SP)           Automática              17911.208107
Perua/SW             São Paulo (SP)           Automática              18378.042702
Sedã                 Rio Grande do Sul (RS)   Manual                  18394.092756
                     Paraná (PR)              Automática              18525.084443
                     São Paulo (SP)           Automática              19757.196092
Perua/SW             Paraná (PR)              Manual                  19906.360817
Hatchback            Santa Catarina (SC)      Manual                  20047.460314
Picape               Paraná (PR)              Manual                  20759.094206
                     São Paulo (SP)           CVT                     21414.766620
Hatchback            Paraná (PR)              Manual                  21715.376918
Sedã                 Rio de Janeiro (RJ)      Manual                  22140.445097
                                              Automática              22661.144848
Picape               Santa Catarina (SC)      Manual                  22727.201846
Sedã                 Rio Grande do Sul (RS)   Automática Sequencial   22761.354082
Picape               Amazonas (AM)            Manual                  22935.932232
Hatchback            Rio Grande do Sul (RS)   Automática              24093.833734
                                              Manual                  25006.195653
Sedã                 Paraná (PR)              Manual                  25195.990696
                     Santa Catarina (SC)      Automática              26041.993022
                     Minas Gerais (MG)        Automática              26427.501097
Picape               Rio de Janeiro (RJ)      Automática              26729.716235
Hatchback            Bahia (BA)               Manual                  26838.814537
Sedã                 Rio de Janeiro (RJ)      Automática Sequencial   27136.964283
Hatchback            Santa Catarina (SC)      Automática              27599.208011
Picape               Rio Grande do Sul (RS)   Manual                  27690.976513
Hatchback            Rio de Janeiro (RJ)      Automática              27743.222216
Picape               Bahia (BA)               Manual                  28168.236390
Sedã                 Bahia (BA)               Manual                  28587.340678
Perua/SW             São Paulo (SP)           Manual                  28875.849751
Hatchback            São Paulo (SP)           Automatizada            28954.034946
                     Paraná (PR)              Automática              29328.116594
Picape               Pernambuco (PE)          Manual                  29624.192787
Sedã                 Rio Grande do Sul (RS)   Automática              29881.951721
Hatchback            Minas Gerais (MG)        CVT                     29906.894268
Picape               Goiás (GO)               Manual                  30259.720035
Sedã                 Rio de Janeiro (RJ)      Semi-automática         30359.737719
Hatchback            Rio Grande do Sul (RS)   Automatizada            30407.524868
Sedã      

- Agrupando o dataset pela features tipo, estado e cambio. Foi selecionado os menores preços de acordo com o agrupamento.
- Dessa forma o carro do tipo Sedão do Estado de Santa Catarina, de cambio manual custa 9869.950645.
- Hatchback, no estado de São Paulo, Manual custa 13576.401422.
- Carro do tipo Picape, do estado de São Paulo, Manual, custa em torne de 13642.891063.
- Carro do tipo Picape, do estado de São Paulo, Automático, custa em torne de 15953.204811

- Caso o cliente seja de algum estádo especifico e deseja que seu carro tenha garantia, qual o valor que ele deve pagar?

- Usando o agrupamento por estado e garantia, e aplicando a função minimo e maximo para cada grupo, podemos ver que o valor minimo e maximo que o cliente deve pagar para ter garantia em cada estado.

- Podemos agrupar também por tipo e cambio, para ver o valor minimo e maximo que o cliente deve pagar.

In [10]:
cars_train.groupby(["estado_vendedor","garantia_de_fábrica"]).agg({"preco":"min"}).sort_values(by="preco",ascending=False)

preco
estado_vendedor          garantia_de_fábrica               
Sergipe (SE)             Garantia de fábrica  308356.595507
Tocantins (TO)           Garantia de fábrica  243002.217032
Mato Grosso (MT)         Garantia de fábrica  178934.006888
Ceará (CE)               Garantia de fábrica  123939.878795
Paraíba (PB)             Garantia de fábrica   95762.746630
Mato Grosso do Sul (MS)  Garantia de fábrica   85730.862915
Acre (AC)                Garantia de fábrica   72811.745577
Pernambuco (PE)          Garantia de fábrica   55243.838003
Alagoas (AL)             Garantia de fábrica   55178.097786
Amazonas (AM)            Garantia de fábrica   54908.191330
Rio Grande do Norte (RN) Garantia de fábrica   54848.887128
Rio Grande do Sul (RS)   Garantia de fábrica   54742.833352
Espírito Santo (ES)      Garantia de fábrica   49919.575982
Goiás (GO)               Garantia de fábrica   45812.306967
Santa Catarina (SC)      Garantia de fábrica   44004.769748
Pará (PA)                Garantia de fábrica   43906.629995
Rio de Janeiro (RJ)      Garantia de fábrica   39556.398656
Bahia (BA)               Garantia de fábrica   33100.914663
São Paulo (SP)           Garantia de fábrica   31763.159542
Minas Gerais (MG)        Garantia de fábrica   29906.894268
Paraná (PR)              Garantia de fábrica   29328.116594

In [11]:
cars_train.groupby(["estado_vendedor","garantia_de_fábrica","tipo"]).agg({"preco":"max"}).sort_values(by="preco",ascending=False)

preco
estado_vendedor          garantia_de_fábrica tipo                               
São Paulo (SP)           Garantia de fábrica Cupê                  677129.123324
Santa Catarina (SC)      Garantia de fábrica Picape                672933.092917
                                             Sedã                  634313.013770
Rio Grande do Sul (RS)   Garantia de fábrica Hatchback             589418.739087
Rio de Janeiro (RJ)      Garantia de fábrica Picape                486869.600468
Goiás (GO)               Garantia de fábrica Cupê                  486648.154645
Rio de Janeiro (RJ)      Garantia de fábrica Utilitário esportivo  467062.082048
São Paulo (SP)           Garantia de fábrica Utilitário esportivo  466310.166751
Sergipe (SE)             Garantia de fábrica Utilitário esportivo  464786.417184
Goiás (GO)               Garantia de fábrica Sedã                  462943.628304
Rio Grande do Sul (RS)   Garantia de fábrica Sedã                  461509.949378
Santa Catarina (SC)      Garantia de fábrica Utilitário esportivo  457695.010807
São Paulo (SP)           Garantia de fábrica Picape                452072.114416
                                             Sedã                  430230.489990
Rio Grande do Sul (RS)   Garantia de fábrica Picape                429538.653910
Paraná (PR)              Garantia de fábrica Utilitário esportivo  429236.244325
Minas Gerais (MG)        Garantia de fábrica Picape                426790.142244
Rio de Janeiro (RJ)      Garantia de fábrica Sedã                  425495.004467
Goiás (GO)               Garantia de fábrica Picape                423958.389539
Paraná (PR)              Garantia de fábrica Picape                421912.148840
Goiás (GO)               Garantia de fábrica Utilitário esportivo  412803.033455
Minas Gerais (MG)        Garantia de fábrica Utilitário esportivo  401745.521038
Santa Catarina (SC)      Garantia de fábrica Cupê                  394770.966611
Rio Grande do Sul (RS)   Garantia de fábrica Utilitário esportivo  393295.426774
Paraná (PR)              Garantia de fábrica Sedã                  390035.259980
São Paulo (SP)           Garantia de fábrica Hatchback             386233.735929
Minas Gerais (MG)        Garantia de fábrica Sedã                  363230.145245
Paraná (PR)              Garantia de fábrica Cupê                  361203.336487
Alagoas (AL)             Garantia de fábrica Utilitário esportivo  353250.074635
Rio Grande do Sul (RS)   Garantia de fábrica Cupê                  352887.071311
Bahia (BA)               Garantia de fábrica Utilitário esportivo  351109.005575
                                             Picape                345435.078334
Alagoas (AL)             Garantia de fábrica Picape                345006.894744
Bahia (BA)               Garantia de fábrica Sedã                  344355.040259
Sergipe (SE)             Garantia de fábrica Picape                328272.278075
Rio de Janeiro (RJ)      Garantia de fábrica Cupê                  305099.183295
Rio Grande do Norte (RN) Garantia de fábrica Utilitário esportivo  302058.400392
Pernambuco (PE)          Garantia de fábrica Utilitário esportivo  282732.009352
Rio de Janeiro (RJ)      Garantia de fábrica Hatchback             272700.766073
Paraná (PR)              Garantia de fábrica Hatchback             271498.265754
Pernambuco (PE)          Garantia de fábrica Picape                268303.679610
Alagoas (AL)             Garantia de fábrica Sedã                  261985.267235
Tocantins (TO)           Garantia de fábrica Picape                243002.217032
Santa Catarina (SC)      Garantia de fábrica Hatchback             232780.981759
Acre (AC)                Garantia de fábrica Picape                228022.077115
Mato Grosso do Sul (MS)  Garantia de fábrica Sedã                  223508.570609
Mato Grosso (MT)         Garantia de fábrica Picape                216380.126235
Pernambuco (PE)          Garantia de fábrica Sedã                  203566.261010
Goiás (GO)               

In [12]:
cars_train.groupby(["estado_vendedor","garantia_de_fábrica","tipo","cambio"]).agg({"preco":"max"}).sort_values(by="preco",ascending=False)

preco
estado_vendedor          garantia_de_fábrica tipo                 cambio                         
São Paulo (SP)           Garantia de fábrica Cupê                 Automática        677129.123324
Santa Catarina (SC)      Garantia de fábrica Picape               Automática        672933.092917
                                             Sedã                 Automática        634313.013770
Rio Grande do Sul (RS)   Garantia de fábrica Hatchback            Automática        589418.739087
Rio de Janeiro (RJ)      Garantia de fábrica Picape               Automática        486869.600468
Goiás (GO)               Garantia de fábrica Cupê                 Automática        486648.154645
Rio de Janeiro (RJ)      Garantia de fábrica Utilitário esportivo Automática        467062.082048
São Paulo (SP)           Garantia de fábrica Utilitário esportivo Automática        466310.166751
Sergipe (SE)             Garantia de fábrica Utilitário esportivo Automática        464786.417184
Goiás (GO)               Garantia de fábrica Sedã                 Automática        462943.628304
Rio Grande do Sul (RS)   Garantia de fábrica Sedã                 Automática        461509.949378
Santa Catarina (SC)      Garantia de fábrica Utilitário esportivo Automática        457695.010807
São Paulo (SP)           Garantia de fábrica Picape               Automática        452072.114416
                                             Sedã                 Automática        430230.489990
Rio Grande do Sul (RS)   Garantia de fábrica Picape               Automática        429538.653910
Paraná (PR)              Garantia de fábrica Utilitário esportivo Automática        429236.244325
Minas Gerais (MG)        Garantia de fábrica Picape               Automática        426790.142244
Rio de Janeiro (RJ)      Garantia de fábrica Sedã                 Automática        425495.004467
Goiás (GO)               Garantia de fábrica Picape               Automática        423958.389539
Paraná (PR)              Garantia de fábrica Picape               Automática        421912.148840
Goiás (GO)               Garantia de fábrica Utilitário esportivo Automática        412803.033455
Minas Gerais (MG)        Garantia de fábrica Utilitário esportivo Automática        401745.521038
São Paulo (SP)           Garantia de fábrica Picape               Automatizada      396769.745550
Santa Catarina (SC)      Garantia de fábrica Cupê                 Automática        394770.966611
Rio Grande do Sul (RS)   Garantia de fábrica Utilitário esportivo Automática        393295.426774
Paraná (PR)              Garantia de fábrica Sedã                 Automática        390035.259980
São Paulo (SP)           Garantia de fábrica Hatchback            Automática        386233.735929
Rio Grande do Sul (RS)   Garantia de fábrica Picape               Automatizada      366105.318381
Minas Gerais (MG)        Garantia de fábrica Sedã                 Automática        363230.145245
Paraná (PR)              Garantia de fábrica Cupê                 Automática        361203.336487
Alagoas (AL)             Garantia de fábrica Utilitário esportivo Automática        353250.074635
Rio Grande do Sul (RS)   Garantia de fábrica Cupê                 Automática        352887.071311
Santa Catarina (SC)      Garantia de fábrica Picape               Automatizada      351394.060101
Bahia (BA)               Garantia de fábrica Utilitário esportivo Automática        351109.005575
São Paulo (SP)           Garantia de fábrica Hatchback            Automatizada      350211.320145
Bahia (BA)               Garantia de fábrica Picape               Automática        345435.078334
Alagoas (AL)             Garantia de fábrica Picape               Automática        345006.894744
Rio de Janeiro (RJ)      Garantia de fábrica Sedã                 Automatizada      344837.569879
Bahia (BA)               Garantia de fábrica Sedã                 Automática        344355.040259
São Paulo (SP)           Garantia de fábrica Utilitário esportivo Manual  

- Usando o agrupamento estao e garantia os melhore estado para comprar um carro de acordo com seu valor com garantia seria Paraná, com o menor valor.
- Usando o agrupamento estado e tipo de carro, o melhor estado para comprar um carro de marca popular seria o Acre(Hacthback), Espírito Santo(Picape), São Paulo(Miniva), Paraíba(Sedã), Espirito Santo(Utilitário esportivo), Rio de Janeiro(Cupê) com o menor valor.
- Contudo adicionando o tipo do carro e a transmissão, o melhor estado para comprar um carro com garantia seria o Rio de Janeiro(Picape, CVT).
- Logo, a escolha de um carro depende do estado, se têm garantion, tipo e o cambio.

- Plotando o gráfico em histograma para visualizar a distribuição

In [13]:
size_columns:int = 2
fig, axl = plt.subplots(size_columns, 2, figsize=(100, 100), constrained_layout=True)
axl[0][0].hist(cars_train['preco'], bins=100)
axl[0][0].set_title('Histograma de Preço')
axl[0][0].set_xlabel('Preço')
axl[0][0].set_ylabel('Frequência')

axl[0][1].hist(cars_train['ano_de_fabricacao'], bins=100)
axl[0][1].set_title('Histograma de Ano de Fabricação')
axl[0][1].set_xlabel('Ano de Fabricação')
axl[0][1].set_ylabel('Frequência')

axl[1][0].hist(cars_train['hodometro'], bins=100)
axl[1][0].set_title('Histograma de Hodômetro')
axl[1][0].set_xlabel('Hodômetro')
axl[1][0].set_ylabel('Frequência')

axl[1][1].hist(cars_train['ano_modelo'], bins=100)
axl[1][1].set_title('Histograma de Ano do Modelo')
axl[1][1].set_xlabel('Ano do Modelo')
axl[1][1].set_ylabel('Frequência')



plt.show()

In [14]:
columns_list:list = cars_train.columns.tolist()
dataframe_a_c: pd.DataFrame = pd.DataFrame(columns=["Assimetria", "Curtose"])
for column in columns_list:
    try:
        data_c:pd.DataFrame = pd.DataFrame(data={"Assimetria": [cars_train[column].skew()], "Curtose": [cars_train[column].kurtosis()]},index=[column])
        dataframe_a_c = pd.concat([dataframe_a_c, data_c], ignore_index=False)
    except TypeError:
        print("Variavel Categorica")
dataframe_a_c

Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica
Variavel Categorica


Assimetria    Curtose
id                  -0.005866  -1.196656
num_fotos            1.001368  -0.651002
ano_de_fabricacao   -2.493793   9.189095
ano_modelo          -0.498640  -0.522504
hodometro            0.590908   1.194606
num_portas          -5.544991  28.797600
entrega_delivery     1.482702   0.198419
troca                1.747047   1.052243
elegivel_revisao     0.000000   0.000000
veiculo_alienado          NaN        NaN
preco                2.148999  10.974860

- Com base nos valores de assimetria e curtose, podemos classificar a curva de densidade estatística do tipo platicútica(ano_modelo) e leptocúritica(preco, ano de fabricacao, hodometro).
- é observado a presença de outlier em preço e ano de fabricação.
- Existem também picos de frequencia em faixas de Hodometro, Ano de Modelo

# Pre-Processamento

- Para o pre-processamento dos dados, foi utilizado o pacote pandas, para a análise exploratória de dados foi utilizado o pacote seaborn e para a modelagem foi utilizado o pacote scikit-learn.
- Inicialmente, será realizado uma transformação das variaveis categoricase e das os variaveis nulas, usando factorize e fillna do pandas, para que possam ser utilizadas nos modelos de machine learning.

In [15]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import KFold
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.model_selection import cross_validate


- Como já foi dito anteriomento, nesta parte será transformado as variaveis do tipo nulo para os valores -1.

In [16]:
cars_train.fillna(-1,inplace=True)
cars_test.fillna(-1,inplace=True)

- Nesta parte será realizado a aplicação do factoriza do pandas para variaveis categoricas

In [17]:
cars_train[[
    'marca',
    'modelo',
    'versao',
    'tipo',
    'cambio',
    'cor',
    'tipo_vendedor',
    'cidade_vendedor',
    'estado_vendedor',
    'anunciante',
    'entrega_delivery',
    'troca',
    'elegivel_revisao',
    'dono_aceita_troca',
    'revisoes_concessionaria',
    'ipva_pago',
    'veiculo_licenciado',
    'garantia_de_fábrica',
    'revisoes_dentro_agenda',
    'blindado', 'veiculo_único_dono']] = cars_train[[
    'marca',
    'modelo',
    'versao',
    'tipo',
    'cambio',
    'cor',
    'tipo_vendedor',
    'cidade_vendedor',
    'estado_vendedor',
    'anunciante',
    'entrega_delivery',
    'troca',
    'elegivel_revisao',
    'dono_aceita_troca',
    'revisoes_concessionaria',
    'ipva_pago',
    'veiculo_licenciado',
    'garantia_de_fábrica',
    'revisoes_dentro_agenda',
    'blindado', 'veiculo_único_dono']].apply(lambda x: pd.factorize(x)[0])

In [18]:
cars_test[[
    'marca',
    'modelo',
    'versao',
    'tipo',
    'cambio',
    'cor',
    'tipo_vendedor',
    'cidade_vendedor',
    'estado_vendedor',
    'anunciante',
    'entrega_delivery',
    'troca',
    'elegivel_revisao',
    'dono_aceita_troca',
    'revisoes_concessionaria',
    'ipva_pago',
    'veiculo_licenciado',
    'garantia_de_fábrica',
    'revisoes_dentro_agenda',
    'blindado', 'veiculo_único_dono']] = cars_test[[
    'marca',
    'modelo',
    'versao',
    'tipo',
    'cambio',
    'cor',
    'tipo_vendedor',
    'cidade_vendedor',
    'estado_vendedor',
    'anunciante',
    'entrega_delivery',
    'troca',
    'elegivel_revisao',
    'dono_aceita_troca',
    'revisoes_concessionaria',
    'ipva_pago',
    'veiculo_licenciado',
    'garantia_de_fábrica',
    'revisoes_dentro_agenda',
    'blindado', 'veiculo_único_dono']].apply(lambda x: pd.factorize(x)[0])

- Separação dos dados X e Y do dataset

In [19]:
price:list[float] = cars_train["preco"].tolist()
cars_train.drop(columns=["preco"], inplace=True)

- Instanciação do objeto MinMaxScaler, para normalização dos dados

In [20]:
scaler = MinMaxScaler()

In [21]:
scaler.fit(cars_train)
normaliza_train:pd.DataFrame = pd.DataFrame(scaler.transform(cars_train))
scaler.fit(cars_test)
normaliza_test:pd.DataFrame = pd.DataFrame(scaler.transform(cars_test))

- Após a aplicação das transformações, foi feito uma analise de correlação entre as variaveis, para verificar se havia alguma variavel que poderia ser removida por ter uma correlação muito alta com outra variavel.
- Para escolha das features foi utilizado a classe SelectKBest do sklearn, que utiliza o teste estatistico f regression para selecionar as features.

In [45]:
Nk = SelectKBest(f_regression, k=2)
x_train = Nk.fit_transform(normaliza_train, price)
x_test = Nk.transform(normaliza_test)

## Escolha do Modelo de Machine Learning

- Nesta parte foi escolhido os modelos Elastic Net, Ridge e Lasso para serem treinados e avaliados.
- Para mensurar a enficência dos modelos foi utilizado o RMSE e o ME, MSE.
- O para enconctra o paramentro alpha foi utilizado o GridSearchCV.
- e para o processo de validação, foi usado a validação cruzadda com 5 folds.

In [87]:
def train_test_validate_regresao(regressao, x_train, x_test, y_train):
    kfold =  KFold(n_splits=5, random_state=42, shuffle=True)
    model = regressao()
    param_grid = {'alpha': list(range(1,11))}
    model_hp = GridSearchCV(model, param_grid, cv=kfold)
    scores = cross_validate(model_hp, x_train, y_train, cv=kfold, scoring=("explained_variance","max_error","neg_mean_squared_error"),return_train_score=True)
    model_hp.fit(x_train, y_train)
    predict = model_hp.predict(x_test)
    print(model_hp.best_params_)
    print(scores["train_max_error"])
    print(scores["test_max_error"])
    print(scores["train_neg_mean_squared_error"])
    print(scores["test_neg_mean_squared_error"])
    print(scores["train_explained_variance"])
    print(scores["test_explained_variance"])
    return predict

In [88]:
train_test_validate_regresao(Ridge,x_train, x_test, price)

{'alpha': 1}
[-1176948.55026499 -1177643.22876716 -1178217.02114319  -977135.45589331
 -1176535.49014381]
[ -961721.13400095  -977324.39633837  -849945.66572333 -1177550.34609205
  -652600.82662299]
[-5.88234778e+09 -5.80200139e+09 -5.77596018e+09 -5.70971348e+09
 -5.83479481e+09]
[-5.47596006e+09 -5.79779076e+09 -5.90246152e+09 -6.16644306e+09
 -5.66556423e+09]
[0.12848639 0.12829261 0.13065461 0.13087981 0.13223237]
[0.13706816 0.1371574  0.12779847 0.12713268 0.12123906]


In [89]:
train_test_validate_regresao(Lasso,x_train, x_test, price)

{'alpha': 1}
[-1176167.97517186 -1177043.13149488 -1177714.19686675  -976874.00908029
 -1175755.67614154]
[ -961297.73531245  -976990.6626789   -849503.20620022 -1177119.64201338
  -652932.87403219]
[-5.88226096e+09 -5.80192280e+09 -5.77588915e+09 -5.70964767e+09
 -5.83470664e+09]
[-5.47601612e+09 -5.79738795e+09 -5.90212352e+09 -6.16631985e+09
 -5.66635398e+09]
[0.12849925 0.12830442 0.1306653  0.13088982 0.13224549]
[0.13706299 0.13721737 0.1278492  0.12715027 0.12111662]


In [86]:
train_test_validate_regresao(ElasticNet,x_train, x_test, price)

{'alpha': 1}
[-1226466.76550467 -1226484.48763533 -1226595.59103596 -1020394.4947018
 -1226592.35596365]
[-1006210.89514943 -1020488.52206186  -895130.03198568 -1226392.86957617
  -670728.03878536]
[4.501486807586901e+19, 4.377359332786867e+19, 4.359799939796144e+19, 4.263590319176283e+19, 4.46582830337828e+19]
[3.973977562455683e+19, 4.459331436912976e+19, 4.525980853322671e+19, 4.933128088522089e+19, 4.106355193835253e+19]
[0.00596548 0.00597113 0.00619439 0.00607581 0.00613163]
[0.00642478 0.00618448 0.00581536 0.00584317 0.00608896]


## Conclusão